import type {
  ActGradeName,
  Card,
  OppositionTier,
  PostType,
  Recipe,
  SheetPayload,
  ThreatBucket,
  ThreatPool,
} from "./types";

export const defaultCardCatalog: Card[] = [
  { word: "hunger", color: "Red" },
  { word: "blood", color: "Red" },
  { word: "spark", color: "Red" },
  { word: "chain", color: "Red" },
  { word: "drum", color: "Red" },
  { word: "blush", color: "Red" },
  { word: "fang", color: "Red" },
  { word: "mirror", color: "Blue" },
  { word: "ledger", color: "Blue" },
  { word: "brine", color: "Blue" },
  { word: "map", color: "Blue" },
  { word: "silence", color: "Blue" },
  { word: "frost", color: "Blue" },
  { word: "ink", color: "Blue" },
  { word: "root", color: "Green" },
  { word: "cough", color: "Green" },
  { word: "moss", color: "Green" },
  { word: "seed", color: "Green" },
  { word: "vine", color: "Green" },
  { word: "balm", color: "Green" },
  { word: "marrow", color: "Green" },
  { word: "bell", color: "Gold" },
  { word: "crown", color: "Gold" },
  { word: "coin", color: "Gold" },
  { word: "guard", color: "Gold" },
  { word: "torch", color: "Gold" },
  { word: "oath", color: "Gold" },
  { word: "banner", color: "Gold" },
  { word: "dream", color: "Violet" },
  { word: "veil", color: "Violet" },
  { word: "star", color: "Violet" },
  { word: "echo", color: "Violet" },
  { word: "mask", color: "Violet" },
  { word: "door", color: "Violet" },
  { word: "omen", color: "Violet" },
  { word: "ash", color: "Black" },
  { word: "grave", color: "Black" },
  { word: "rot", color: "Black" },
  { word: "shadow", color: "Black" },
  { word: "bone", color: "Black" },
  { word: "debt", color: "Black" },
  { word: "knife", color: "Black" },
  { word: "mercy", color: "White" },
  { word: "saint", color: "White" },
  { word: "silver", color: "White" },
  { word: "candle", color: "White" },
  { word: "prayer", color: "White" },
  { word: "witness", color: "White" },
  { word: "linen", color: "White" },
];

export const colorStyles: Record<string, string> = {
  Red: "border-chroma-red/40 bg-chroma-red/10 text-chroma-red-ink",
  Blue: "border-chroma-blue/40 bg-chroma-blue/10 text-chroma-blue-ink",
  Green: "border-chroma-green/40 bg-chroma-green/10 text-chroma-green-ink",
  Gold: "border-chroma-gold/40 bg-chroma-gold/10 text-chroma-gold-ink",
  Violet: "border-chroma-violet/40 bg-chroma-violet/10 text-chroma-violet-ink",
  Black: "border-stone-700/60 bg-stone-900 text-stone-50",
  White: "border-stone-300 bg-white text-stone-950",
};

export const chromaNames = Object.keys(colorStyles);

export type Tone = "accent" | "Red" | "Blue" | "Green" | "Gold" | "Violet";

export const toneColorVars: Record<Tone, string> = {
  accent: "var(--color-accent)",
  Red: "var(--color-chroma-red)",
  Blue: "var(--color-chroma-blue)",
  Green: "var(--color-chroma-green)",
  Gold: "var(--color-chroma-gold)",
  Violet: "var(--color-chroma-violet)",
};

export const postTypeTones: Record<PostType, Tone> = {
  act: "Red",
  breathe: "Blue",
  setup: "Gold",
  ghost: "Violet",
};

export const oppositionTierLabels: Record<OppositionTier, string> = {
  obstacle: "Obstacle",
  threat: "Threat",
  trial: "Trial",
};

export const oppositionTierTones: Record<OppositionTier, Tone> = {
  obstacle: "Gold",
  threat: "Red",
  trial: "Violet",
};

export const oppositionTierHints: Record<OppositionTier, string> = {
  obstacle: "Resolves on one Hit. A locked door, a guard, a collapsing bridge.",
  threat: "A 2-3 segment progress track. Hit fills 1, Strong Hit fills 2, Breakthrough clears it.",
  trial: "2-4 conditions, resolved in any order across multiple Beats. Hide some behind Discovery.",
};

export const defaultThreat: ThreatPool = {
  Peril: 0,
  Intrigue: 0,
  Dread: 0,
};

export const threatBucketStyles: Record<ThreatBucket, string> = {
  Peril: "border-chroma-red/40 bg-chroma-red/10 text-chroma-red-ink",
  Intrigue: "border-chroma-blue/40 bg-chroma-blue/10 text-chroma-blue-ink",
  Dread: "border-chroma-violet/40 bg-chroma-violet/10 text-chroma-violet-ink",
};

export const threatBucketByColor: Record<string, ThreatBucket> = {
  Red: "Peril",
  Black: "Peril",
  Blue: "Intrigue",
  Gold: "Intrigue",
  White: "Intrigue",
  Green: "Dread",
  Violet: "Dread",
};

export const gradeBonus: Record<ActGradeName, number> = {
  Incomplete: 0,
  Partial: 0,
  Complete: 2,
  Heightened: 3,
};

export const defaultRecipeCatalog: Recipe[] = [
  {
    id: "bell-cracker-cut",
    name: "Bell-Cracker Cut",
    family: "Strike",
    coreTags: ["violence", "weapon", "force", "command", "sound"],
    chroma: ["Red", "Gold"],
    hit: "Break, silence, interrupt, or disable an object, alarm, voice, weapon, or power source.",
    strongHit: "Also remove, change, or corrupt one Scene Word.",
    miss: "It breaks loudly or dangerously. Add Threat, spend Gear, or trigger Pressure.",
  },
  {
    id: "blood-for-the-door",
    name: "Blood for the Door",
    family: "Strike / Sway",
    coreTags: ["violence", "sacrifice", "force", "oath", "passage"],
    chroma: ["Red", "Black"],
    hit: "Force passage through something that wants payment.",
    strongHit: "You choose what it takes.",
    miss: "It opens and takes more than you offered.",
  },
  {
    id: "saint-stone-intercession",
    name: "Saint-Stone Intercession",
    family: "Shelter",
    coreTags: ["defense", "protection", "oath", "healing", "faith"],
    chroma: ["White", "Blue"],
    hit: "Protect someone from supernatural, moral, psychic, or memory-based harm.",
    strongHit: "Also reveal what the danger wanted from them.",
    miss: "You protect them, but the danger marks you instead.",
  },
  {
    id: "brace-the-threshold",
    name: "Brace the Threshold",
    family: "Shelter",
    coreTags: ["defense", "place", "passage", "craft", "protection"],
    chroma: ["White", "Gold"],
    hit: "Secure a doorway, room, camp, or vulnerable position.",
    strongHit: "Create a Setup Word tied to the secured place.",
    miss: "It holds only if someone stays, pays, or is exposed.",
  },
  {
    id: "pilgrims-read",
    name: "Pilgrim's Read",
    family: "Uncover",
    coreTags: ["memory", "knowledge", "perception", "ritual", "oath", "trace"],
    chroma: ["Blue", "White"],
    hit: "Interpret sacred marks, vows, paths, warnings, relics, or ritual architecture.",
    strongHit: "Ask an additional question or reveal a hidden route.",
    miss: "You learn the truth by triggering part of it.",
  },
  {
    id: "follow-the-slip",
    name: "Follow the Slip",
    family: "Uncover",
    coreTags: ["memory", "perception", "truth", "speech", "suspicion", "attention"],
    chroma: ["Blue", "Gold"],
    hit: "Turn an NPC's slip into a concrete lead.",
    strongHit: "They don't realize what they revealed.",
    miss: "You get the lead, but they know you noticed.",
  },
  {
    id: "false-key",
    name: "False Key",
    family: "Distort",
    coreTags: ["deception", "lock", "secrecy", "shadow", "magic", "passage"],
    chroma: ["Blue", "Black"],
    hit: "Bypass, deceive, or confuse a lock, seal, ward, watcher, or gate.",
    strongHit: "It remains fooled after you pass.",
    miss: "It opens, but something knows.",
  },
  {
    id: "ashen-veil",
    name: "Ashen Veil",
    family: "Distort",
    coreTags: ["concealment", "shadow", "magic", "deception", "fear", "death"],
    chroma: ["Black", "Violet"],
    hit: "Hide yourself, obscure an ally, or blur a scene boundary.",
    strongHit: "Create a temporary Black or Violet Setup Word.",
    miss: "You vanish from the wrong thing or attract something worse.",
  },
  {
    id: "quiet-crossing",
    name: "Quiet Crossing",
    family: "Move",
    coreTags: ["motion", "stealth", "passage", "patience", "water", "shadow"],
    chroma: ["Blue", "Green"],
    hit: "Move through danger without raising Alert.",
    strongHit: "Bring someone or something with you safely.",
    miss: "You arrive, but Pressure advances.",
  },
  {
    id: "mercy-purchase",
    name: "Mercy Purchase",
    family: "Sway / Shelter",
    coreTags: ["mercy", "trust", "care", "healing", "debt", "oath", "speech"],
    chroma: ["White", "Green"],
    hit: "Gain trust by addressing a need, pain, fear, or vulnerability.",
    strongHit: "The NPC offers more than you asked for.",
    miss: "The need becomes your responsibility.",
  },
  {
    id: "soft-confession",
    name: "Soft Confession",
    family: "Sway",
    coreTags: ["speech", "truth", "vulnerability", "guilt", "oath", "memory"],
    chroma: ["White", "Blue"],
    hit: "Lower suspicion or make someone answer one question without hostility.",
    strongHit: "They reveal what they wish you hadn't asked.",
    miss: "You reveal more than intended.",
  },
  {
    id: "knife-under-the-table",
    name: "Knife Under the Table",
    family: "Sway / Distort",
    coreTags: ["threat", "fear", "deception", "violence", "speech", "status"],
    chroma: ["Red", "Black"],
    hit: "Force a concession through menace, blackmail, or implied violence.",
    strongHit: "They comply without public escalation.",
    miss: "They escalate, call help, or mark you as dangerous.",
  },
];

export const defaultSheet: SheetPayload = {
  name: "Serit Vane",
  pronouns: "they/them",
  concept: "Oathbreaker knight of the drowned gate",
  focus: 3,
  thread: 0,
  core_words: [
    { id: 1, word: "cleave", tags: "violence, weapon, force" },
    { id: 2, word: "shelter", tags: "defense, protection, oath" },
    { id: 3, word: "confess", tags: "speech, truth, vulnerability" },
    { id: 4, word: "endure", tags: "defense, body, guilt" },
  ],
  marks: [],
  wounds: [],
  gear: [
    {
      id: 1,
      name: "Rusted Sword",
      tags: ["weapon", "violence", "oath"],
      chroma: "",
      guard: 0,
      guard_max: 0,
      supply: 0,
      supply_max: 0,
      tapped: false,
    },
    {
      id: 2,
      name: "Pilgrim Shield",
      tags: ["defense", "protection", "oath", "cover"],
      chroma: "",
      guard: 2,
      guard_max: 2,
      supply: 0,
      supply_max: 0,
      tapped: false,
    },
    {
      id: 3,
      name: "Delver's Pack",
      tags: ["supply", "travel", "utility"],
      chroma: "",
      guard: 0,
      guard_max: 0,
      supply: 3,
      supply_max: 3,
      tapped: false,
    },
  ],
  tie: "I will not abandon Mara - but I abandoned the gate once.",
  hand: [
    { word: "hunger", color: "Red" },
    { word: "mercy", color: "White" },
    { word: "mirror", color: "Blue" },
    { word: "crown", color: "Gold" },
  ],
  deck: defaultCardCatalog.filter((card) =>
    [
      "blood",
      "chain",
      "silence",
      "brine",
      "saint",
      "candle",
      "bell",
      "oath",
      "ash",
      "bone",
      "debt",
      "echo",
      "door",
      "balm",
      "root",
    ].includes(card.word),
  ),
  discard: [],
};
